-- Migration 010: Add a permanent, immutable per-member index number
--
-- The admin dashboard's ranged Excel export ("rows 6500-6800") previously used
-- LIMIT/OFFSET over created_at DESC, which shifts every existing row's position
-- whenever a new member registers. member_index is assigned once (in original
-- registration order) and never changes, so a given range always resolves to
-- the same members regardless of later inserts/deletes.
--
-- GENERATED BY DEFAULT (not ALWAYS) so existing rows can be explicitly backfilled.
-- Run against your Supabase project via the SQL editor or CLI.

BEGIN;

LOCK TABLE public.member_profiles IN SHARE ROW EXCLUSIVE MODE;

ALTER TABLE public.member_profiles
  ADD COLUMN member_index bigint GENERATED BY DEFAULT AS IDENTITY;

WITH ordered AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY created_at ASC, id ASC) AS rn
  FROM public.member_profiles
)
UPDATE public.member_profiles mp
SET member_index = ordered.rn
FROM ordered
WHERE mp.id = ordered.id;

-- Continue the identity sequence after the backfilled max so new inserts don't collide.
SELECT setval(
  pg_get_serial_sequence('public.member_profiles', 'member_index'),
  COALESCE((SELECT MAX(member_index) FROM public.member_profiles), 0) + 1,
  false
);

ALTER TABLE public.member_profiles
  ALTER COLUMN member_index SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_member_profiles_member_index
  ON public.member_profiles (member_index);

COMMIT;
