# Official NBA branch list.
# Used for validation of the `branch` field on member profiles.

NBA_BRANCHES: list[str] = [
    "Aba Branch",
    "Abakaliki Branch",
    "Abeokuta Branch",
    "Abuja Branch (Unity Bar)",
    "Ado-Ekiti Branch",
    "Afikpo Branch",
    "Aguata Branch",
    "Ahoada Branch",
    "Akure Branch",
    "Asaba Branch",
    "Auchi Branch",
    "Awka Branch",
    "Badagry Branch",
    "Bauchi Branch",
    "Benin Branch",
    "Bida Branch",
    "Birnin-Kebbi Branch",
    "Biu Branch",
    "Bori Branch",
    "Bwari Branch",
    "Calabar Branch",
    "Damaturu Branch",
    "Degema Branch",
    "Dutse Branch",
    "Effurun",
    "Eket Branch",
    "Ekwulobia",
    "Enugu Branch",
    "Epe Branch",
    "Eti-Osa Branch",
    "Funtua Branch",
    "Garki Branch (Liberty Bar)",
    "Gboko Branch",
    "Gombe Branch",
    "Gusau Branch",
    "Gwagwalada Branch",
    "Ibadan Branch",
    "Idah Branch",
    "Idemili Branch",
    "Ihiala Branch",
    "Ijebu-Ode Branch",
    "Ikeja Branch",
    "Ikere-Ekiti Branch",
    "Ikirun Branch",
    "Ikole-Ekiti Branch",
    "Ikom Branch",
    "Ikorodu Branch",
    "Ikot-Ekpene Branch",
    "Ilaro Branch",
    "Ile-Ife Branch",
    "Ilesa Branch",
    "Ilorin Branch",
    "Isiala Ngwa Branch",
    "Isiokpo Branch",
    "Iwo Branch",
    "Jalingo Branch",
    "Jos Branch",
    "Kaduna Branch",
    "Kafanchan Branch",
    "Kano Branch",
    "Katsina Branch",
    "Keffi Branch",
    "Lafia Branch",
    "Lagos Branch",
    "Lokoja Branch",
    "Maiduguri Branch",
    "Makurdi Branch",
    "Minna Branch",
    "Mubi Branch",
    "Nsukka Branch",
    "Obollo-Afor",
    "Ogbomoso Branch",
    "Ogoja Branch",
    "Okehi Branch",
    "Okene Branch",
    "Okigwe Branch",
    "Okitipupa",
    "Ondo Branch",
    "Onitsha Branch",
    "Orlu Branch",
    "Osogbo Branch",
    "Otukpo Branch",
    "Otuocha",
    "Owerri Branch",
    "Owo Branch",
    "Oyo Branch",
    "Pankshin Branch",
    "Port Harcourt Branch",
    "Sagamu Branch",
    "Sagbama Branch",
    "Sapele Branch",
    "Shendam Branch",
    "Sokoto Branch",
    "Suleja Branch",
    "Ughelli Branch",
    "Umuahia Branch",
    "Uyo Branch",
    "Warri Branch",
    "Yenagoa Branch",
    "Yola Branch",
    "Zaria Branch",
]

NBA_BRANCHES_SET: set[str] = set(NBA_BRANCHES)
